database = "wordnet.db"
wordnet_source = "/home/john-mccrae/p/globalwordnet/english-wordnet/src/yaml/"
semcor_database = "semcor.db"
semcor_source = "/home/john-mccrae/p/globalwordnet/semcor/semcor.yaml"
logo = "assets/english.svg"
theme = "assets/styling/theme.css"
project_name = "Open English Wordnet"
footer = """
<p class="footer1">
    Open English Wordnet is derived from <a href="http://wordnet.princeton.edu/">Princeton WordNet</a>
    by the Open English Wordnet Community and released under the
    <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution (CC-BY) 4.0 License</a>.
    <a href="https://globalwordnet.github.io/gwadoc/">Further information about Wordnet</a>.
    We welcome any corrections, improvements or other contributions at
    <a href="http://github.com/globalwordnet/english-wordnet">GitHub</a>.
    A full list of contributors is available on
    <a href="https://github.com/globalwordnet/english-wordnet/blob/master/README.md">GitHub</a>.
</p>
<p class="footer2">
    This interface was created by <a href="http://john.mccr.ae/">John P. McCrae</a> at the
    <a href="https://dsi.nuigalway.ie/">Data Science Institute</a>,
    <a href="http://www.universityofgalway.ie">University of Galway</a>
    (<a href="http://github.com/jmccrae/ewe">GitHub</a>). Development of this interface is supported by
    <a href="https://www.sfi.ie/">Science Foundation Ireland</a> as part of the
    <a href="https://www.insight-centre.org/">Insight Centre for Data Analytics</a>
    and the European Union's Horizon 2020 research and innovation programme under grant agreement No 731015
    (<a href="http://elex.is/">ELEXIS</a>).
</p>
"""
