on:
  push:
    tags:
      - 'v*'

name: cargo-win

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release -p ewe-cli
      - run: cp target/release/ewe-cli.exe ewe-cli-windows.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ewe-cli-windows.exe
          prerelease: false
          generate_release_notes: true
